server:
  port: 8071
  
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
      
  instance:
    hostname: host.docker.internal
    prefer-ip-address: true
    
spring:
  jpa:
    hibernate: 
      ddl-auto: none
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/bd_bootcoin
      username: root
      password: s3cr3ct
      driver-class-name: com.mysql.jdbc.Driver  