server:
  port: 8072
  
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
      
  instance:
    hostname: host.docker.internal
    prefer-ip-address: true
    
spring:
  jpa:
    hibernate: 
      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bd_bank
    username: root
    password: s3cr3ct
    driver-class-name: com.mysql.cj.jdbc.Driver 